"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/navbar";
import Footer from "@/components/layout/footer/footer";

import { usePathname } from "next/navigation";

import Providers from "@/redux/store/provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const pathname = usePathname();


  // pages where navbar & footer should NOT appear
  const hideLayoutRoutes = [
    // '/login',
    // '/signup',
    '/auth/login',
    '/auth/register',
    '/auth/otpverification',
    '/auth/forgetPassword',
    '/auth/resetPassword',
    '/dashboard',

  ]

  const hideLayout = hideLayoutRoutes.includes(pathname)


  return (
    <html lang="en">






      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {!hideLayout && <Navbar />}
          {children}
          {!hideLayout && <Footer />}
        </Providers>

      </body>
    </html>
  );
}
